# Generated by Django 3.1a1 on 2020-05-31 19:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=50, verbose_name='Organizer')),
                ('location', models.CharField(max_length=100, verbose_name='Location where the event was held')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField()),
                ('Event_date', models.DateTimeField(verbose_name='Event Date')),
                ('Event_poster', models.FileField(blank=True, null=True, upload_to='', verbose_name='Add Photo to Event')),
                ('Event_type', models.CharField(choices=[('1', 'Core Group Meeting'), ('2', 'Club Meeting'), ('3', 'Workshop'), ('4', 'Staff & PI Meetings'), ('6', 'Other Events')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Writer')),
            ],
            options={
                'ordering': ['-Event_date', '-Event_type'],
            },
        ),
    ]
