# Generated by Django 3.1a1 on 2020-05-29 21:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Professor_name')),
                ('department', models.CharField(max_length=50, verbose_name='Expertise of Professor')),
                ('email', models.EmailField(max_length=254, verbose_name='Email id')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="student's name")),
                ('department', models.CharField(max_length=50, verbose_name='Department of Student')),
                ('email', models.EmailField(max_length=254, verbose_name='Email id')),
                ('position', models.CharField(max_length=50, verbose_name='Course the student is Pursuing & year')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField()),
                ('Project_date', models.DateTimeField(verbose_name='Project Completion Date')),
                ('Project_poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Add Photo to product')),
                ('Project_report', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Add Report of project')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Writer')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.professor', verbose_name='professors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.student', verbose_name='students')),
            ],
            options={
                'ordering': ['-Project_date'],
            },
        ),
    ]
