# Generated by Django 3.1a1 on 2020-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_report',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add Report of project in pdf Format'),
        ),
    ]
