# Generated by Django 3.1a1 on 2020-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreports',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='projectreport',
            field=models.ManyToManyField(blank=True, null=True, to='projects.Projectreports'),
        ),
    ]
