# Generated by Django 3.1a1 on 2020-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_date',
            field=models.DateField(blank=True, null=True, verbose_name='Project Starting Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='member',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
