# Generated by Django 3.1a1 on 2020-06-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200602_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectreport',
        ),
        migrations.AddField(
            model_name='projectreports',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
