# Generated by Django 3.1a1 on 2020-06-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200602_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreports',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='projectreports',
            field=models.ManyToManyField(related_name='reports', to='projects.Projectreports'),
        ),
    ]
