# Generated by Django 3.1a1 on 2020-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation Date'),
        ),
    ]
