# Generated by Django 3.1a1 on 2020-06-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of the person contacting')),
                ('email', models.EmailField(max_length=254, verbose_name='email of the person contacting')),
                ('query', models.CharField(max_length=1000, verbose_name='Query of the person')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time of Querying')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Member')),
                ('position', models.CharField(choices=[('0', 'RuTAG Club - trainee'), ('1', 'RuTAG Club - Project Member'), ('2', 'RuTAG Club - Project Leader'), ('3', 'RuTAG Club - Club Coordinator'), ('4', 'RuTAG Club - Club principal'), ('5', 'RuTAG Club - Club Secratary'), ('6', 'Core - Jr. Project Assistant'), ('7', 'Core - Sr. Project Assistant'), ('8', 'Core - Club Principal Inspector'), ('9', 'Core - Chairman'), ('10', 'Core - PI'), ('11', 'Core - Jr. Project Attendant'), ('12', 'Core - Project Associate'), ('13', 'Core - Coordinator and Principal Investigator (PI)'), ('14', 'Core - Chairman, Core Group'), ('15', 'Core - Web Developer'), ('16', 'Research Scholar')], max_length=50, verbose_name='position of the member')),
                ('image', models.ImageField(default='/static/default.jpg', upload_to='', verbose_name='Profile Picture of the Member')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Some detail about the Member')),
                ('email', models.EmailField(default='rutagiitd@gmail.com', max_length=254, verbose_name='email id of the member')),
                ('work', models.CharField(choices=[('0', 'Core'), ('1', 'Club')], default='0', max_length=20, verbose_name='Area of Working')),
                ('level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
            ],
        ),
    ]
