# Generated by Django 3.1a1 on 2020-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='work',
            field=models.CharField(choices=[('0', 'Core'), ('1', 'Club')], default='0', max_length=20, verbose_name='Area of Working'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('0', 'RuTAG Club - trainee'), ('1', 'RuTAG Club - Project Member'), ('2', 'RuTAG Club - Project Leader'), ('3', 'RuTAG Club - Club Coordinator'), ('4', 'RuTAG Club - Club principal'), ('5', 'RuTAG Club - Club Secratary'), ('6', 'Core - Jr. Project Assistant'), ('7', 'Core - Sr. Project Assistant'), ('8', 'Core - Club Principal Inspector'), ('9', 'Core - Chairman'), ('10', 'Core - PI'), ('11', 'Core - Jr. Project Attendant'), ('12', 'Core - Project Associate'), ('13', 'Core - Coordinator and Principal Investigator (PI)'), ('14', 'Core - Chairman, Core Group'), ('15', 'Core - Web Developer'), ('16', 'Research Scholar')], max_length=50, verbose_name='position of the member'),
        ),
    ]
